# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b63fcf28566d81e0d7f11a49b006e66bd7818a3e13b2eb5db6819b443650d1032e8822d4d85f1ccc066bd8b71c7bbd5f39f24f966dca51a733be4d4d2fa62df7

test:
  secret_key_base: fc3b3a4540077a34e8792d43837583d33c810ecb07a6f1a751afe4df96086aafb18e88a8c29ea2c8cf35a1db9d7b39abb1acbccf76ba6dd815e0dbec931009ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
